# Generated by Django 3.1.3 on 2021-01-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210118_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
