# Generated by Django 3.1.3 on 2021-01-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0015_order_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('zip_code', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('nip', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
