# Generated by Django 3.1.3 on 2021-01-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210119_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='ha7thanh@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
