# Generated by Django 3.1.3 on 2021-01-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
