# Generated by Django 3.1.3 on 2021-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20210125_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nip',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
