# Generated by Django 3.1.3 on 2021-01-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210126_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nip',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
