# Generated by Django 3.1.3 on 2021-01-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20210126_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_added',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_added',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_added',
            new_name='release_date',
        ),
    ]
