# Generated by Django 3.1.3 on 2021-01-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
