# Generated by Django 3.1.3 on 2021-02-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20210207_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
