# Generated by Django 3.1.3 on 2021-02-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20210207_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('d', 'delivery'), ('b', 'bank')], default='d', max_length=1),
        ),
    ]
