# Generated by Django 3.1.3 on 2021-02-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
