# Generated by Django 3.1.3 on 2021-02-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20210208_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
