# Generated by Django 3.2.3 on 2021-05-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20210528_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalVat',
            new_name='total_vat',
        ),
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
