# Generated by Django 3.2.3 on 2021-05-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20210531_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_vat',
            new_name='brutto',
        ),
    ]
